### ISSUE TITLE
Wikidata - backend

### ISSUE THREAD

**Issue by JarbasAI** [ElliotTheRobot/LILACS-mycroft-core#16]
currently scraps following node info:

```
    Node:
       name: node name
       parents: [ what ]
       childs:
       synonims:
       antonims:
       cousins:
       Attributes:
            description: wikidata description_field
            data: {wikidata_dict}
            props: [wikidata_properties]
```

should parse properties for connections

-------------------------
original issue:

a backend should be made to adquire knowledge from wikidata #4 

wikidata connects subjects in useful ways, we should keep an eye on properties: 
https://tools.wmflabs.org/hay/propbrowse/ 

we should map the correct properties to either childs or parents, or even as arbitrary data connections #10 

this seems the most well structured source for our purpose, surfing github for stuff of this kind i found this promising start -> https://github.com/Dorialexander/Wikidaesthetics
