### ISSUE TITLE
Wikipedia - Backend

### ISSUE THREAD

**Issue by JarbasAI** [ElliotTheRobot/LILACS-mycroft-core#17]
Currently scraps following node info:

```
    Node:
       name: node name
       parents: []
       childs:
       synonims:
       antonims:
       cousins: []
       Attributes:
            summary: wikipedia_summary
            links: [ wikipedia link ]
            pics: [ wikipedia pic ]
            infobox: {wikipedia infobox}
```

____________________

original issue:

a backend should be made to adquire knowledge from wikipedia #4

wikipedia is better for info than to connect nodes, we should add to the arbitrary data of each node #10

- summary from wiki
- parse wiki tables for fields and add to arbitrary data
- try to match table fields to parents/child connections

wikipedia skill should be replaced by this backend and blacklisted / refactored as a different skill
