### ISSUE TITLE
DBPedia - Backend

### ISSUE THREAD

**Issue by JarbasAI** [ElliotTheRobot/LILACS-mycroft-core#23]
Currently scrapes following node info:
```
    Node:
       name: node name
       parents: [ dbpedia types]
       childs:
       synonims:
       antonims:
       cousins: [ dbpedia_related_subjects, dbpedia_see_also]
       Attributes:
            abstract: dbpedia abstract
            links: [ dbpedia link ]
            pics: [ dbpedia pic ]
            external_links[ suggested links from dbpedia]
```

------------------------------------------------------------------
original issue:

dbpedia provides easy acess to stuctured from wiki sources, while probably not getting much new info spotlight allows for concept tagging

this backend can be used by the question parser #21 and a crawler #19  to get nodes

https://github.com/dbpedia-spotlight/dbpedia-spotlight/wiki

```
sentence: what are living beings

score : 0.673143505346
subject: living beings
offset: 9
type: 
link: http://dbpedia.org/resource/Jiva


sentence: the dog eats meat that comes from a cow and is an animal

score : 0.999819349173
subject: dog
offset: 4
type: DBpedia:Species
type: DBpedia:Eukaryote
type: DBpedia:Animal
type: DBpedia:Mammal
link: http://dbpedia.org/resource/Dog

score : 0.987413174929
subject: meat
offset: 13
type: 
link: http://dbpedia.org/resource/Meat

score : 0.984556205445
subject: cow
offset: 36
type: DBpedia:Species
type: DBpedia:Eukaryote
type: DBpedia:Animal
type: DBpedia:Mammal
link: http://dbpedia.org/resource/Cattle

score : 0.927415670462
subject: animal
offset: 50
type: DBpedia:Species
type: DBpedia:Eukaryote
type: DBpedia:Animal
link: http://dbpedia.org/resource/Animal

```
